# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Complete workflow

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
        mongodb-version: [4.2]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.1.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}

    - name: Install dependencies
      run: npm install

    - name: Run all tests
      run: npm test

    - name: Deploy application
    if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
    uses: akhileshns/heroku-deploy@v3.12.12
    with:
      heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      heroku_app_name: "wsl-forecast"
      heroku_email: "wslmacieira@gmail.com"
